---
title: "_P. vivax_ Among Asymptomatic Adults in the DRC"
author: "Nicholas F. Brazeau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center')

Sys.setenv(RSTUDIO_PANDOC="/usr/local/Cellar/pandoc/2.7.3/bin/")

```

```{r, child = 'analyses/03-covar_assoc/02-analyze_corr.Rmd'}
```

```{r, child = 'analyses/04-Univar_Bivar_Assoc.Rmd'}
```

```{r, child = 'analyses/05-basic_mapping.Rmd'}
```

```{r, child = 'analyses/06-IPW_ML/00-kmeans_DRC.Rmd'}
```

```{r, child = 'analyses/06-IPW_ML/02-check_weights.Rmd'}
```

```{r, child = 'analyses/06-IPW_ML/03-MSM_RRest.Rmd'}
```

```{r, child = 'analyses/07-spatial_prediction/01-Pv_areal_CAR_MCMC.Rmd'}
```

```{r, child = 'analyses/07-spatial_prediction/02-Pv_clst_map_GaussianProc_MCMC_frontend.Rmd'}
```

```{r, child = 'analyses/07-spatial_prediction/03-Pv_get_predictions.Rmd'}
```

```{r, child = 'analyses/08-species_interference.Rmd'}
```

```{r, child = 'analyses/09-Power/02-collect_powercalcs.Rmd'}
```
