---
title: "IPTW Risk Factor Prevalence Ratios"
author: "Nicholas F. Brazeau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, eval = T, results = 'hide')
```

```{r}
library(tidyverse)
devtools::install_github("malcolmbarrett/ggdag"); library(ggdag)

```


## DAG
Note, the canonical set is all nodes in the DAG that are not on the casual pathway (i.e. "mediators"). By including the canonical set, we have taken a conservative approach for controlling for "lingering" or "unmeasured" confounders. 
  
```{r, results='asis', fig.align='center', fig.width=8, fig.height=6}
vividdag <- dagitty::downloadGraph(x = "dagitty.net/mjKNQhB")
tidy_dag <- tidy_dagitty(vividdag)
DAGplot <- ggdag(tidy_dag) +
  theme_dag()

dagplot <- tidy_dag %>% 
  ggplot(aes(x = x, y = y, xend = xend, yend = yend, color = name)) +
  geom_dag_point() +
  geom_dag_edges() +
  geom_dag_text(color = "#ef3b2c", size = 2) +
  theme_dag() +
  scale_color_viridis_d() + 
  theme(legend.position = "none")



plot(dagplot)

jpeg(filename = "~/Documents/GitHub/VivID_Epi/results/figures/dag.jpg",
     width = 11, height = 8, units = "in", res=500)
plot(dagplot)
graphics.off()



```


## _P. vivax_ Risk Factor IPTW-Prevelance Ratios
```{r}
#.......................
# Pvivax 
#.......................
pvivrskfctr <- dcdr$column_name[dcdr$risk_factor_model == "y"]
pvivrskfctr_models <- data.frame(outcome = rep("pv18s", length(pvivrskfctr)), 
                                 covar = pvivrskfctr, stringsAsFactors=FALSE)

pvivrskfctr_models$glmlogit <- purrr::pmap(pvivrskfctr_models, .f=fitsvyglmlogit)
pvivrskfctr_models$glmlogit_tidy <- purrr::map(pvivrskfctr_models$glmlog,
                                               .f=function(x){
                                                 broom::tidy(x, exponentiate=TRUE, conf.int=TRUE)}
)
pvivrskfctr_est <- pvivrskfctr_models$glmlogit_tidy %>% 
  bind_rows() %>% filter(term != "(Intercept)") %>% 
  mutate_if(is.numeric, round, 2)

```


## _P. falciparum_ Risk Factor IPTW-Prevelance Ratios
```{r}
#.......................
# Pfalciparum 
#.......................
pfalrskfctr <- dcdr$column_name[dcdr$risk_factor_model == "y" & dcdr$column_name != "pfldh_fctb"]
pfalrskfctr <- c("pv18s_fctb", pfalrskfctr)
pfalrskfctr_models <- data.frame(outcome = rep("pfldh", length(pfalrskfctr)), 
                                 covar = pfalrskfctr, stringsAsFactors=FALSE)

pfalrskfctr_models$glmlogit <- purrr::pmap(pfalrskfctr_models, .f=fitsvyglmlogit)


pfalrskfctr_models$glmlogit_tidy <- purrr::map(pfalrskfctr_models$glmlogit,
                                               .f=function(x){
                                                 broom::tidy(x, exponentiate=TRUE, conf.int=TRUE)})


pfalrskfctr_est <- pfalrskfctr_models$glmlogit_tidy %>% 
  bind_rows() %>% filter(term != "(Intercept)") %>% 
  mutate_if(is.numeric, round, 2)


```