--- 
title: "EDA" 
author: "Nick Brazeau" 
date: "`r format(Sys.time(), '%B %d, %Y')`" 
output: 
  html_document: 
    highlight: tango 
    theme: lumen 
    toc: yes 
    toc_float: yes 
    toc_depth: 3 
    result_folding: hide 
editor_options:  
  chunk_output_type: console
--- 
```{r, echo=F, message=F, warning=F}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
devtools::install_github("OJWatson/rdhs", ref="master")
library(rdhs)

```
# Overview

```{r, echo=F, message=F, warning=F}
proj_dir <- "~/Documents/GitHub/VivID_PhD_Thesis/VivIDRiskFactorAnalysis/"
setwd(file.path(proj_dir))
rdhs::set_rdhs_config(email = "nbrazeau@med.unc.edu",
                      project = "Infectious Disease Epidemiology of DRC", 
                      config_path = "rdhs.json", 
                      global = FALSE,
                      cache_path = "~/Documents/GitHub/VivID_PhD_Thesis/VivIDRiskFactorAnalysis/")


survs <- dhs_surveys(surveyCharacteristicIds = 89,
                     countryIds = c("CD"),
                     surveyYearStart = 2013)


datasets <- dhs_datasets(surveyIds = survs$SurveyId, 
                         fileFormat = "flat")
str(datasets)
get_datasets(datasets$FileName)




### test
pkg_dir <- "~/Documents/GitHub/rdhs/tests/testthat/"
devtools::test(pkg_dir)



t <- readRDS("~/Documents/GitHub/VivID_PhD_Thesis/VivIDRiskFactorAnalysis//datasets/CDPR61FL.rds")
## check to see if reformat does what you want

## what aobout barcode in PR


```

## Data Munging
Pull in 2013 DHS. 
```{r, echo=F, message=F, warning=F}

# https://ojwatson.github.io/rdhs/articles/introduction.html



datasets <- dhs_datasets(surveyIds = "CD2013DHS",
                         fileFormat = "flat")

dt <- get_datasets("CDAR61FL.ZIP")

```




