--- 
title: "Univariate and Bivariate Analyses" 
author: "Nick Brazeau" 
date: "`r format(Sys.time(), '%B %d, %Y')`" 
output: 
  html_document: 
    highlight: tango 
    theme: lumen 
    toc: yes 
    toc_float: yes 
    toc_depth: 3 
    result_folding: hide 
editor_options:  
  chunk_output_type: console
--- 

# Overview

**Outcome (binary)**: _P. vivax infection (i.e. parasitemia detectable by RT-PCR)

The variables that I care about as potential EMM & Confounders (or other variables of interest/bookkeeping) are: 
## Risk Factors


  1. barcode (i.e. Sample ID)
  2. PFLDH (result of Pfalciparum RT-PCR scoring system) **outcome**
  2. HumBT (whether or not human beta-tubulin was in a sample -- a good positive control per sample)
  2. PFLDH_parasitemia_mean
  2. HumBT_ngperuL_mean
  3. FCq_mean (i.e. CT mean for Pf)
  4. VCq_mean (i.e. CT mean for human)
  6. cluster
  7. household
  7. HIV Status (HIV03)
  7. Sample Weight from HIV dataset (HIV05)
  7. Household Sample Weight (HV005)
  7. Number of household members (HV009)
  7. Number of Children in Household under 5 (HV014)
  7. Province (HV024)
  7. Type of Residence i.e. Rural or Urban (HV025)
  7. Place of Residence (HV026)
  7. Cluster altitude (HV040)
  7. Drinking Water (categorical: HV201)
  7. Non-Drinking water (categorical: HV202)
  7. Type of Tolilet Facility (categorical: HV205)
  7. Has Electricity (HV206)
  7. Has Radio (HV207)
  7. Has television (HV208)
  7. Has refrigerator (HV209)
  7. Has bicycle (HV210)
  7. Has motorcycle/scooter (HV211)
  7. Has car/truck (HV212)
  7. Main floor material (categorical: HV213)
  7. Main wall material (categorical: HV214)
  7. Main roof material (categorical: HV215)
  7. Number of rooms for sleeping (HV216)
  7. Has Telephone (HV221)
  7. Shares toilet with other household (HV225)
  8. Owns Mosquite ned for sleeping (HV227)
  8. CHildren under 5 slept under net (HV228)
  8. Owns livestock, herds, of farms (HV246)
  8. Owns cows/bulls (HV246B)
  8. Owns horses/donkeys/mules (HV246C)
  8. Wealth Index (HV270)
  8. Wealth Index Factor (HV271)
  8. Number of mosquito bed needs (HML1A)
  8. SHPOOL 
  9. SHNPROVIN
  9. Biological Sex (HV104)
  9. Age (HV105)
  10. Highest year of education attained (categorical: HV106) -- note there is something very weird going on with this varibale?!!?
  10. Highest year of education completed (continous: HV107) -- note there is something very weird going on with this varibale?!!?
  10. Education Completed in Single Years (continous: HV108) -- note there is something very weird going on with this varibale?!!?
  10. Educational Attainment (Categorical: HV109)
  10. Hemoglobin Level adjust for altitude and smoking (HA56 & HB56)
  10. Currently pregnant? (HA54)
  10. Anemia Level (HA57 & HB57)
  10. Net Observed by interviewer (HML3)
  10. Months ago net obtained (HML4)
  10. Net treated with insecticide (HML5)
  10. Net Treatment Status (HML6)
  10. Brand of Net (HML7)
  10. Net treated since recieving (HML8)
  10. Time since last re-treatment (HML9)
  10. Insecticide-Treated Net (HML10)
  10. Number of person who slept under net (HML11)
  10. Pregnancy status from Individual file (HML18)
  10. Person slept under an ever-treated net (HML19)
  10. Person slept under an LLIN net (HML20)
  10. Microscopy (HML32)
  10. RDT (HML35)

* Note HA variables are for female blood tests only and HB are for male only blood tests

```{r}

source("analyses/00-functions.R") 
library(tidyverse)
library(sf)
library(srvyr) #wrap the survey package in dplyr syntax
#......................
# Import Data
#......................
load("data/vividepi_raw.rda")
dt <- merge_pr_plsmdm_gemtdt(pr = arpr, plsmdm = panplasmpcrres, ge = ge)

pvage <- dt %>% 
    dplyr::mutate(hv005 = hv005/1e5,
                hiv05 = hiv05/1e5) %>% 
    srvyr::as_survey_design(ids = hv001, weights = hv005) %>% 
    dplyr::group_by(hv105) %>% 
    dplyr::summarise(plsmdn = srvyr::survey_total(hv001), 
                     plsmd = srvyr::survey_mean(pv18s, na.rm = T, vartype = c("se", "ci"), level = 0.95))
pvage$species <- "vivax"
pfage <- dt %>% 
    dplyr::mutate(hv005 = hv005/1e5,
                hiv05 = hiv05/1e5) %>% 
    srvyr::as_survey_design(ids = hv001, weights = hv005) %>% 
    dplyr::group_by(hv105) %>% 
    dplyr::summarise(plsmdn = srvyr::survey_total(), 
                     plsmd = srvyr::survey_mean(pfldh, na.rm = T, vartype = c("se", "ci"), level = 0.95))
pfage$species <- "falciparum"

plotObj <- dplyr::bind_rows(pvage, pfage) %>% 
  ggplot() + 
  geom_line(aes(x=hv105, y=plsmd, color = species)) + 
  geom_ribbon(aes(x=hv105, ymin=plsmd_low, ymax=plsmd_upp, fill = species), alpha=0.5) +
  geom_point(aes(x=hv105, y=plsmd, size=plsmdn, color = species), alpha=0.5, show.legend=F) +
  scale_fill_manual("Malara Species", values = c("#a50026", "#313695"), labels = c("Pfalciparum", "Pvivax")) +
  scale_colour_manual(values = c("#a50026", "#313695"), guide =F) +
  ggtitle("Malaria Prevalence by Age") +
  xlab("Age") + ylab("Malaria Prevalence") +
  theme(plot.title = element_text(family = "Helvetica", face = "bold", size = 15, hjust = 0.5, vjust = 0.5),
        axis.text.x=element_text(angle=90,hjust=1, vjust=0.5, family = "Helvetica", face = "bold", size=8),
        axis.text.y=element_text(family = "Helvetica", face = "bold", size=8),
        axis.title.x=element_text(family = "Helvetica", face = "bold", size=10),
        axis.title.y=element_text(family = "Helvetica", face = "bold", size=10),
        axis.line = element_line(colour = "black", size=2),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom")



jpeg(filename = "~/Desktop/agegraph.jpg", width = 11, height = 6, units = "in", res=300)
plot(plotObj)
graphics.off()



```

