---
title: "Malaria Species Interference"
author: "Nicholas F. Brazeau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide')
```

```{r}
remotes::install_github("nickbrazeau/icer")
library(tidyverse)
library(icer)
source("~/Documents/GitHub/VivID_Epi/R/00-functions_basic.R")

#......................
# Import Data
#......................
dt <- readRDS("~/Documents/GitHub/VivID_Epi/data/derived_data/vividepi_recode_completecases.rds")
dtsrvy <- makecd2013survey(survey = dt)

# need weighed counts
data <- dtsrvy %>% 
  dplyr::mutate(pfmono =  ifelse(pfldh == 1 & pv18s == 0 & po18s == 0, 1, 0),
                pvmono =  ifelse(pfldh == 0 & pv18s == 1 & po18s == 0, 1, 0),
                pomono =  ifelse(pfldh == 0 & pv18s == 0 & po18s == 1, 1, 0),
                pfpv =  ifelse(pfldh == 1 & pv18s == 1 & po18s == 0, 1, 0),
                pfpo =  ifelse(pfldh == 1 & pv18s == 0 & po18s == 1, 1, 0),
                pvpo =  ifelse(pfldh == 0 & pv18s == 1 & po18s == 1, 1, 0),
                pfpvpo =  ifelse(pfldh == 1 & pv18s == 1 & po18s == 1, 1, 0)
  ) %>% 
  dplyr::summarise(
    "pf" = srvyr::survey_total(x=pfmono),
    "pv" = srvyr::survey_total(x=pvmono),
    "po" = srvyr::survey_total(x=pomono),
    "pf/pv" = srvyr::survey_total(x=pfpv),
    "pf/po" = srvyr::survey_total(x=pfpo),
    "pv/po" = srvyr::survey_total(x=pvpo),
    "pf/pv/po" = srvyr::survey_total(x=pfpvpo)
  ) %>% 
  dplyr::select(-c(dplyr::ends_with("_se")))



data.vec <- unlist(data)
# have to round 
data.vec <- round(data.vec, 0)

```

## Infection Composition Model (from Multinomial)
```{r}
surv <- new("surveillance")
surv@denominator <- 15859
surv@cases <- unlist(data.vec)
surv@casenames <- names(data.vec)



```

We will use 50,000 iterations. 

### Indepdent Model for Interference 
```{r}

# assuming independence
surv.mle <- icer::cooccurence_mle(obj = surv, 
                      density_func = icer:::independent,
                      max_moi = 25, poisson = T, plot = T, boot_iter = 5e4) 



```

### Cluster Level Prevalences-Interactions
```{r}
mp <- readRDS(file = "~/Documents/GitHub/VivID_Epi/data/derived_data/basic_cluster_mapping_data.rds")
ge <- sf::st_as_sf(readRDS(file = "~/Documents/GitHub/VivID_Epi/data/raw_data/dhsdata/datasets/CDGE61FL.rds")) %>% 
  magrittr::set_colnames(tolower(colnames(.))) %>% 
  dplyr::rename(hv001 = dhsclust)


pfpvclst <- mp %>% 
  dplyr::filter(plsmdmspec %in% c("pfldh", "pv18s") & maplvl == "hv001") %>% 
  dplyr::ungroup() %>% 
  dplyr::select(c("plsmdmspec", "data")) 

# issue with casting from sf
pf <- pfpvclst$data[[1]]
pfclust <- cbind.data.frame(species = "pf", pf) %>% 
  dplyr::select(c("species", "hv001", "plsmdprev", "n"))
pv <- pfpvclst$data[[2]]
pvclust <- cbind.data.frame(species = "pv", pv) %>% 
  dplyr::select(c("species", "hv001", "plsmdprev", "n"))

pfpvclst <- left_join(pfclust, pvclust, by = c("hv001", "n")) %>% 
  dplyr::left_join(., y = ge, by = "hv001")


```

```{r, results='asis'}

pfpvclst %>% 
  ggplot() + 
  geom_point(aes(x=plsmdprev.x, y = plsmdprev.y, size = n)) +
  geom_smooth(aes(x=plsmdprev.x, y = plsmdprev.y, weight = n), method=loess) +
  facet_wrap(~ urban_rura) +
  xlab("Pfalciparum") + ylab("Pvivax") + 
  labs(title ="Cluster Level Prevalences Seperated \n by Urbanicity",
       caption = "Loess line and point sizes are weighted by cluster size") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(vjust = 0.5, hjust = 0.5))
               


```
